[constants]
qt_prefix       = 'C:/Qt/5.15.2/msvc2019_64'
gst_prefix      = 'C:/gst-install'

[built-in options]
auto_features       = 'disabled'
default_library     = 'static'
vsenv               = true
prefix              = gst_prefix
pkg_config_path     = gst_prefix / 'lib/pkgconfig'
force_fallback_for  = ['zlib', 'libffi', 'proxy-libintl', 'pcre2', 'glib', 'graphene', 'libnice', 'vpx', 'openh264', 'orc']
pkgconfig.relocatable = true

[project options]
libnice = 'enabled'
orc = 'enabled'
orc-source = 'subproject'
qt5 = 'enabled'
ugly = 'disabled'
webrtc = 'enabled'

[glib:project options]
tests = false

[libnice:project options]
gstreamer = 'enabled'
crypto-library = 'openssl'

[orc:project options]
tools = 'enabled'

[vpx:project options]
examples = 'disabled'
tools = 'disabled'
docs = 'disabled'
multi_res_encoding = 'enabled'
postproc = 'enabled'
size_limit = '16384x16384'
temporal_denoising = 'enabled'
vp8_decoder = 'enabled'
vp8_encoder = 'enabled'
vp9_decoder = 'enabled'
vp9_encoder = 'enabled'
vp9_temporal_denoising = 'enabled'
vp9_postproc = 'enabled'
vp9_highbitdepth = 'enabled'

[gst-plugins-base:project options]
app = 'enabled'
audioconvert = 'enabled'
audiomixer = 'enabled'
audioresample = 'enabled'
audiotestsrc = 'enabled'
gl = 'enabled'
gl-graphene = 'enabled'
gl_api = 'opengl'
gl_platform = 'wgl'
gl_winsys = 'win32'
opus = 'enabled'
playback = 'enabled'
videoconvertscale = 'enabled'
videorate = 'enabled'
volume = 'enabled'

[gst-plugins-good:project options]
isomp4 = 'enabled'
qt5 = 'enabled'
qt-method = 'qmake'
rtp = 'enabled'
rtpmanager = 'enabled'
vpx = 'enabled'

[gst-plugins-bad:project options]
asio = 'enabled'
audiolatency = 'enabled'
d3d11 = 'enabled'
debugutils = 'enabled'
dtls = 'enabled'
mediafoundation = 'enabled'
openh264 = 'enabled'
proxy = 'enabled'
sctp = 'enabled'
srtp = 'enabled'
videoparsers = 'enabled'
webrtc = 'enabled'
wasapi2 = 'enabled'

[binaries]
qmake5 = qt_prefix / 'bin/qmake.exe'
# Don't accidentally pick up anything from the system other than Qt
cmake = 'false'
pkg-config = gst_prefix / 'bin/pkg-config'
